[
    {
        "Soil High": 7.5,
        "Water max": 1015,
        "Lat1": 25,
        "Soil Type": "Good drainage critical. Rich, deep loam certainly contributes to maximum growth, but grows well in sand, gravel, and even oolitic limestone.Low tolerance for salts, boron and lawn herbicides . Like a very low total water salt contnat of 0.04-0.05%. Soils should have a depth of at least 1.2 m or more. Water table should be at 1.8-2.4m",
        "Commodity": "Mango",
        "Lat2": -25,
        "Variety": "Francis",
        "Water min": 890,
        "Sunlight": "bright sunny days and moderate humidity during flowering",
        "Elevation High": 915,
        "Tº low": 23.9,
        "Tº High": 26.7,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5.5
    },
    {
        "Soil High": 6.5,
        "Water max": 1100,
        "Lat1": 30,
        "Soil Type": "Loamy, well drained (dark brown and  reddish brown balsaltic and sandy loams preferred), slightly acidic",
        "Commodity": "Pineapple",
        "Lat2": -30,
        "Variety": "Hawaiian",
        "Water min": 1000,
        "Sunlight": "full sun, few clouds",
        "Elevation High": 800,
        "Tº low": 18,
        "Tº High": 32,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 4.5
    },
    {
        "Soil High": 7.5,
        "Water max": 2000,
        "Lat1": 30,
        "Soil Type": "Prefers soils with clay content < 18%.  Will not tolerate saline or waterlogged conditions. Under commercial conditions cassava extracts from the soil the following nutrients: 253 Kg N/Ha; 28 kg P/Ha; 250 kg K/Ha; 42 kg Ca/Ha; 29 kg Mg/Ha.  Well adapted to acid soils, but does not do well with low zinc levels",
        "Commodity": "Yucca/Cassava",
        "Lat2": -30,
        "Variety": "Data needed",
        "Water min": 1900,
        "Sunlight": "Full sun, high humidity, see notes on day length",
        "Elevation High": 2000,
        "Tº low": 25,
        "Tº High": 29,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5.5
    },
    {
        "Soil High": 8,
        "Water max": 2000,
        "Lat1": 30,
        "Soil Type": "Soil preparation should be deep, about 20 cm, and thorough. Roselle requires a permeable soil, a friable sandy loam with humus being preferable",
        "Commodity": "Hibiscus (roselle)",
        "Lat2": -30,
        "Variety": "Data needed",
        "Water min": 1500,
        "Sunlight": "A sunny western or southern exposure that has  bright, direct light is best, hot dry, high humidity plant",
        "Elevation High": 900,
        "Tº low": 25,
        "Tº High": 35,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 4.5
    },
    {
        "Soil High": 6.7,
        "Water max": 2000,
        "Lat1": 32,
        "Soil Type": "While doing best in light, porous soils rich in organic matterPapayas perform best on deep that are well drained. Heavy clay soils or acidic soils are not ideal. A topsoil depth of 1 m is preferable for optimum growth and production, and a minimum depth of 0.5 m is essential to avoid waterlogging",
        "Commodity": "Papaya",
        "Lat2": -23,
        "Variety": "Data needed",
        "Water min": 1500,
        "Sunlight": "Full sun to light shade",
        "Elevation High": 1000,
        "Tº low": 23,
        "Tº High": 27,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5.5
    },
    {
        "Soil High": 8.7,
        "Water max": 700,
        "Lat1": 23,
        "Soil Type": "The tree tolerates a great diversity of soil types, from deep alluvial soil to rocky land and porous, oolitic limestone. It withstands salt spray and can be planted fairly close to the seashore.The tree  deep alluvial, well-drained soils of loamy texture.",
        "Commodity": "Tamarind",
        "Lat2": -23,
        "Variety": "Data needed",
        "Water min": 500,
        "Sunlight": "Likes direct sun, humidity",
        "Elevation High": 1500,
        "Tº low": 20,
        "Tº High": 29,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 4.5
    },
    {
        "Soil High": 8,
        "Water max": 700,
        "Lat1": 50,
        "Soil Type": "well-drained loamy soils",
        "Commodity": "Maize",
        "Lat2": -40,
        "Variety": "Data needed",
        "Water min": 500,
        "Sunlight": "12.5 hours/day being suggested as the ",
        "Elevation High": 4000,
        "Tº low": 16.7,
        "Tº High": 23.3,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5
    },
    {
        "Soil High": 6.5,
        "Water max": 1000,
        "Lat1": 23,
        "Soil Type": "good water retention capacity with good amount of clay and organic matter are ideal for rice cultivation",
        "Commodity": "Rice",
        "Lat2": -23,
        "Variety": "Data needed",
        "Water min": 900,
        "Sunlight": "Full sunlight",
        "Elevation High": 3000,
        "Tº low": 21,
        "Tº High": 37,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5.5
    },
    {
        "Soil High": 8.5,
        "Water max": 750,
        "Lat1": 40,
        "Soil Type": "Soils with clay loam or loam texture, having good water retention capacity",
        "Commodity": "Sorghum",
        "Lat2": -40,
        "Variety": "Data needed",
        "Water min": 400,
        "Sunlight": "Full sunlight",
        "Elevation High": 1500,
        "Tº low": 26,
        "Tº High": 30,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 6
    },
    {
        "Soil High": 7.5,
        "Water max": 430,
        "Lat1": 42,
        "Soil Type": "well\ndrained, fertile loams and lighter clay soils. It tolerates\nloamy to heavy soils but will not do well in waterlogged\nSoils.",
        "Commodity": "barley",
        "Lat2": -70,
        "Variety": "Data needed",
        "Water min": 90,
        "Sunlight": "Full sunlight",
        "Elevation High": 3000,
        "Tº low": 5,
        "Tº High": 27,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 6
    },
    {
        "Soil High": 6.5,
        "Water max": 800,
        "Lat1": 30,
        "Soil Type": "Loam soil also soil with proper system of drainage",
        "Commodity": "Wheat",
        "Lat2": -25,
        "Variety": "Data needed",
        "Water min": 600,
        "Sunlight": "Full sunlight",
        "Elevation High": 4000,
        "Tº low": 20,
        "Tº High": 25,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5.8
    },
    {
        "Soil High": 7,
        "Water max": 1100,
        "Lat1": 20,
        "Soil Type": "well-drained, light- and medium-textured soils ",
        "Commodity": "Sweet potato",
        "Lat2": -40,
        "Variety": "Data needed",
        "Water min": 750,
        "Sunlight": "Full sunlight",
        "Elevation High": 1600,
        "Tº low": 15,
        "Tº High": 33,
        "Elevation Low": 1000,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 4.5
    },
    {
        "Soil High": 6.8,
        "Water max": 1700,
        "Lat1": 33,
        "Soil Type": "fertile, friable soil that has a high water capacit and is rich in organic matte",
        "Commodity": "Taro",
        "Lat2": -33,
        "Variety": "Data needed",
        "Water min": 1500,
        "Sunlight": null,
        "Elevation High": 2400,
        "Tº low": 21,
        "Tº High": 27,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 6
    },
    {
        "Soil High": 7,
        "Water max": 750,
        "Lat1": 7,
        "Soil Type": "It grows best in a well-drained fertile soil",
        "Commodity": "millet",
        "Lat2": -9,
        "Variety": "Data needed",
        "Water min": 250,
        "Sunlight": "Full sunlight",
        "Elevation High": 1800,
        "Tº low": 12,
        "Tº High": 28,
        "Elevation Low": 800,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 6
    },
    {
        "Soil High": 6.5,
        "Water max": 4000,
        "Lat1": 20,
        "Soil Type": "Soil moisture at all depths. deep, fertile, well drained, loose, loams and sandy-loam soils with low levels of salinity",
        "Commodity": "yam",
        "Lat2": -20,
        "Variety": "Data needed",
        "Water min": 1200,
        "Sunlight": "Full sunlight",
        "Elevation High": 1400,
        "Tº low": 17,
        "Tº High": 35,
        "Elevation Low": 0,
        "nutritional value (calories)": "116 / 6%",
        "Best Season": null,
        "Soil min": 5.5
    },
    {
        "Soil High": 7,
        "Water max": 1700,
        "Lat1": 36.7,
        "Soil Type": "The soil should be deep, humus-rich, well aerated and drained",
        "Commodity": "sugarcane",
        "Lat2": -31,
        "Variety": "Data needed",
        "Water min": 1500,
        "Sunlight": "Full sunlight",
        "Elevation High": 1700,
        "Tº low": 20,
        "Tº High": 28,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5
    },
    {
        "Soil High": 6.5,
        "Water max": 500,
        "Lat1": 55,
        "Soil Type": "Soybeans are sensitive to low pH",
        "Commodity": "soybeans",
        "Lat2": -55,
        "Variety": "Data needed",
        "Water min": 400,
        "Sunlight": "short-day plant",
        "Elevation High": 2000,
        "Tº low": 21,
        "Tº High": 32,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 6
    },
    {
        "Soil High": 7,
        "Water max": 2000,
        "Lat1": 35,
        "Soil Type": "Rich soils high in organic matter",
        "Commodity": "guava",
        "Lat2": -35,
        "Variety": "Data needed",
        "Water min": 1000,
        "Sunlight": "Full sunlight",
        "Elevation High": 1500,
        "Tº low": 3,
        "Tº High": 32,
        "Elevation Low": 0,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 5
    },
    {
        "Soil High": 7.5,
        "Water max": 1100,
        "Lat1": 20,
        "Soil Type": "The soil on cocoa plantations should be deep, well-drained, and have sufficient water-retaining capacity",
        "Commodity": "cocoa",
        "Lat2": -20,
        "Variety": "Data needed",
        "Water min": 1000,
        "Sunlight": "shade",
        "Elevation High": 700,
        "Tº low": 25,
        "Tº High": 25,
        "Elevation Low": 400,
        "nutritional value (calories)": null,
        "Best Season": null,
        "Soil min": 4
    },
    {
        "Soil High": null,
        "Water max": 1250,
        "Lat1": 23,
        "Soil Type": "Soil with proper drainage, good water-holding capacity.",
        "Commodity": "coconut",
        "Lat2": -60,
        "Variety": "Data needed",
        "Water min": 1100,
        "Sunlight": "Full sunlight",
        "Elevation High": 700,
        "Tº low": 26,
        "Tº High": 27,
        "Elevation Low": 0,
        "nutritional value (calories)": "660 / 33%",
        "Best Season": null,
        "Soil min": null
    },
    {
        "Soil High": 7.5,
        "Water max": 1000,
        "Lat1": 30,
        "Soil Type": "Alluvial and volcanic soils. Rich organic soil",
        "Commodity": "Banana",
        "Lat2": -30,
        "Variety": "Data needed",
        "Water min": 900,
        "Sunlight": "Full sunlight",
        "Elevation High": 1800,
        "Tº low": 27,
        "Tº High": 38,
        "Elevation Low": 0,
        "nutritional value (calories)": "89.0 / 4%",
        "Best Season": null,
        "Soil min": 6
    }
]

